### ISSUE TITLE
Bug You missed the breath bar in the new texture... and more

### ISSUE THREAD

**Issue by SirAron111** [Tfarcenim/ClassicBar#11] opened 2019-04-04 00:05 UTC
![2019-04-04_02 04 20](https://user-images.githubusercontent.com/39855956/55520776-0ae29400-567e-11e9-8f91-01cd26e19c0b.png)

Bug You missed the breath bar in the new texture here is a picture.
hope that helped

**Comment by Tfarcenim** [comment] 2019-04-04 00:07
Dammit

**Comment by Tfarcenim** [comment] 2019-04-04 00:10
Odd i can't seem to reproduce it in 0.1.9

**Comment by Tfarcenim** [comment] 2019-04-04 00:13
![2019-04-03_20 12 13](https://user-images.githubusercontent.com/44327798/55520988-cd194780-564c-11e9-93f2-682b2f97789c.png the hovering bar is caused by the toughness being larger than 0, but still affecting offset

**Comment by SirAron111** [comment] 2019-04-04 19:51
Ok I tested some more and went a bit in-depth with the bugs to try and help you narrow it down.

Ok first of all it’s not because of the texture pack I tested it witouth it.
![2019-04-04_21 28 16](https://user-images.githubusercontent.com/39855956/55583464-3919af80-5722-11e9-8152-caf86ed676b3.png)

It’s also not because of the flight bar or the texture style
![2019-04-04_21 18 30](https://user-images.githubusercontent.com/39855956/55583522-5cdcf580-5722-11e9-8d69-51fc6acdcc36.png)

So I tested if it had something to do with not having the fully drawn armor/toughness bar options so I turned them on but got another bug instead XD (the Bars now Move around)
![2019-04-04_21 16 14](https://user-images.githubusercontent.com/39855956/55583677-c52bd700-5722-11e9-9515-ad4dd23b7b17.png)
![2019-04-04_21 15 35](https://user-images.githubusercontent.com/39855956/55583678-c52bd700-5722-11e9-914a-3a0a801af905.png)
![2019-04-04_21 15 39](https://user-images.githubusercontent.com/39855956/55583679-c52bd700-5722-11e9-9b20-fb4e239b6f87.png)
![2019-04-04_21 15 42](https://user-images.githubusercontent.com/39855956/55583680-c52bd700-5722-11e9-976d-93de4e943ba2.png)
![2019-04-04_21 15 45](https://user-images.githubusercontent.com/39855956/55583681-c5c46d80-5722-11e9-95cc-115f230961e1.png)

So I turned the fully drawn bars back to false and tested the new function of the armor flashing when on low durability (Not a needed function in my opinion) but this one also had a bug XD it kept flashing even when I put the helmet (1 durability) of my head and in my hand. And when I throw it away or simply unequipped it at the right moment when the bar flashes it keeps the current color of the bar flashing and even if I remove the other armor parts or equip it all again it keeps that grayed out color until I put the flashing helmet back on.
![2019-04-04_21 36 10](https://user-images.githubusercontent.com/39855956/55584001-83e7f700-5723-11e9-9334-c07ca20c4a74.png)
![2019-04-04_21 36 01](https://user-images.githubusercontent.com/39855956/55584002-83e7f700-5723-11e9-819a-4250c585cc4d.png)
![2019-04-04_21 36 03](https://user-images.githubusercontent.com/39855956/55584003-83e7f700-5723-11e9-903c-54a8fb2ccd49.png)
![2019-04-04_21 36 04](https://user-images.githubusercontent.com/39855956/55584004-83e7f700-5723-11e9-8ef1-622cf41a1746.png)

So in the end I am sorry I couldn’t narrow it down what caused the water breading bar to not appear in the bars style but hey instead I discovered lots of new bugs …. Glad I could help Xd … Sry!

**Comment by SirAron111** [comment] 2019-04-04 19:54
It is the 0.1.9 version made sure of that

**Comment by Tfarcenim** [comment] 2019-04-04 21:09
Oops, looks like I made a mistake with some braces, will be fixed shortly

**Comment by Khioni** [comment] 2019-04-06 22:43
![image](https://user-images.githubusercontent.com/36409872/55676103-aac93900-589b-11e9-88ae-f89e397669e0.png)
Armor bar flashing and getting stuck when low durability items removed is still a problem in v1.11, also doubt it's intended for it to trigger on equipped item being low durability (including broken in the case of TConstruct tools)

**Closed** 2019-04-30 02:00 UTC
Labels: Fixed, bug, fixed in dev
